implemented a cache for already downloaded models
gizatechxyz/actions-sdk pull request #39
Opened 2024-04-22 10:48 UTC by shivam6862

Implemented a cache for already downloaded models by using the diskcache package  https://github.com/gizatechxyz/actions-sdk/issues/37

2024-04-22 16:06 UTC, Gonmeso commented on giza_actions/model.py
> +                onnx_model = self.version_client.download_original(
Let's change this to use `_download_model` and the read it, so we have the benefits of the cache.

2024-04-22 16:06 UTC, Gonmeso commented on giza_actions/model.py
> +            file = self.version_client.download_original(
We should change this to use `_download_model` which handles the usage of the cache if it does not exist. Currently if this is used multiple times the model would be download each time as is not reflected on the cache.

Lets use `_download_model` and the read.

2024-04-22 18:18 UTC, shivam6862 commented
@Gonmeso requested changes have been made

2024-04-22 19:03 UTC, shivam6862 commented on pyproject.toml
> +diskcache == "5.6.3"
will run  poetry add diskcache

Package operations: 47 installs, 1 update, 0 removals
  - Installing pendulum (2.1.2): Failed
  ChefBuildError
  
Note: This error originates from the build backend, and is likely not a problem with poetry but with pendulum (2.1.2) not supporting PEP 517 builds. You can verify this by running 'pip wheel --no-cache-dir --use-pep517 "pendulum (==2.1.2)"'.

2024-04-23 10:18 UTC, Gonmeso commented on giza_actions/model.py
>              if output_path:
Having to pass `output_path` to `_download_model` and `_get_output_dtype` will mostly make `output_path` to be mandatory, but this is not the intention so another path where if `output_path` is not provided we handle it for the user:

* Lets make the class to have an attribute `self._output_path`
* If `output_path` is present when the user creates the instance, we will use that path, if not we will handle that
* Remove `output_path` argument from `_download_model` and use `self._output_path`
* Remove `output_path` from `_set_session` and `_get_output_dtype` as it is not needed any more

An example of the init could be:

```python
    def __init__(
        self,
        model_path: Optional[str] = None,
        id: Optional[int] = None,
        version: Optional[int] = None,
        output_path: Optional[str] = None,
    ):
       ...

        if model_path:
            self.session = ort.InferenceSession(model_path)
        elif id and version:
            self.model_id = id
            self.version_id = version
            self.model_client = ModelsClient(API_HOST)
            self.version_client = VersionsClient(API_HOST)
            self.api_client = ApiClient(API_HOST)
            self.endpoints_client = EndpointsClient(API_HOST)
            self._get_credentials()
            self.model = self._get_model(id)
            self.version = self._get_version(version)
            self.session = self._set_session()
            self.framework = self.version.framework
            self.uri = self._retrieve_uri()
            self.endpoint_id = self._get_endpoint_id()
            if output_path is not None:
                self._output_path = output_path
            else:
                self._output_path = os.path.join(tempfile.gettempdir(), f"{self.model_id}_{self.version_id}_{self.model.name})
            # Now this internally uses self._output_path
            # As we are using the cache hitting this function should not be problematic
            self._download_model()
```

2024-04-23 10:18 UTC, Gonmeso commented on giza_actions/model.py
> +            cache_str = f"{self.model.id}_{self.version.version}_model"
Let's remove this and use `self._output_path` so cache keys are more consistent

2024-04-23 10:18 UTC, Gonmeso commented on giza_actions/model.py
> +            if cache_str in self._cache:
With the proposed changes
```python
          if self._output_path in self._cache:
                file_path = Path(self._cache.get(self._output_path))
                with open(file_path, "rb") as f:
                    onnx_model = f.read()
```

2024-04-23 10:18 UTC, Gonmeso commented on giza_actions/model.py
> +        cache_str = f"{self.model.id}_{self.version.version}_model"
As in the previous comment, let's remove this and use self._output_path so cache keys are more consistent

2024-04-23 10:18 UTC, Gonmeso commented on giza_actions/model.py
> +            if ".onnx" in output_path:
With the proposed changes this should be `self._output_path`

2024-04-23 10:18 UTC, Gonmeso commented on giza_actions/model.py
> +        output_path: Optional[str] = None,
Remove this as it is not needed

2024-04-23 10:18 UTC, Gonmeso commented on giza_actions/model.py
> +                        output_dtype = self._get_output_dtype(output_path)
This should be as it was before

2024-04-23 10:18 UTC, Gonmeso commented on giza_actions/model.py
> +        cache_str = f"{self.model.id}_{self.version.version}_model"
With the proposed changes this should be `self._output_path`

2024-04-23 10:18 UTC, Gonmeso commented
Testing is still missing, that its why I proposed creating a cache class to test it easily.

2024-04-23 15:12 UTC, shivam6862 commented
@Gonmeso @raphaelDkhn  added a Test for cache and Requested changes have been made

2024-04-24 09:00 UTC, Gonmeso requested changes
Really close to be done!

We just need to fix the tests and this would be ready, as CI is failing. Try to make sure that everything is working previously by running `pytest`

2024-04-24 09:00 UTC, Gonmeso commented on giza_actions/model.py
> +            self._cache = Cache(os.path.join(os.getcwd(), "tmp", "cachedir"))
Cache should be initialized before `_set_session` and `download_model` as if the user does not provide `output_path` set session will try to hit `self._cache` which has not been initialized. 

This is making the previous two existing tests to fail.

2024-04-24 09:00 UTC, Gonmeso commented on tests/test_model.py
> +def test_cache_implementation(*args):
The test is failing as some mocks are missing, the current error is due to missing credentials, for that just add:

```python
@patch("giza_actions.model.GizaModel._get_credentials")
def test_cache_implementation(*args):
```

Also it is possible that some patches are missing as well, for example for `_get_model` and `_get_version`  might be need.

2024-04-24 09:37 UTC, shivam6862 commented
@Gonmeso Added Patch for test and made required changes to pass CI,
I'm looking for some guidance.

2024-04-24 13:34 UTC, Gonmeso commented
Hi!

One little note, making the changes and just waiting CI to pass will make this process longer, it is encouraged to run the tests locally and then push the changes when they pass locally.

The error is the following:

```python
/home/runner/work/actions-sdk/actions-sdk/giza_actions/model.py:206: in _download_model
    onnx_model = self.version_client.download_original(
E   Exception: Token expired or not set. API Key not available. Log in again.
        self       = <giza_actions.model.GizaModel object at 0x7fcfd48[65](https://github.com/gizatechxyz/actions-sdk/actions/runs/8814392110/job/24195017336?pr=39#step:6:66)890>
```

Here we can see that `_download_model` is being executed and the next call in the stack is `self.version_client.download_original` which is trying to get the model from the API and fails to do so without credentials, that means that we need to patch this.

With the recent changes `_download_model`, it is being executed every single time as currently we always handle the output path to use with the cache.

To solve this we could start by patching the `self.version_client.download_original` function. Checking this function, this dependency comes in the `__init__` method:

```python
            self.model_client = ModelsClient(API_HOST)
            self.version_client = VersionsClient(API_HOST) # < This one 
            self.api_client = ApiClient(API_HOST)
            self.endpoints_client = EndpointsClient(API_HOST)
```

In order to patch this, we need to patch the imported client from the script (docs here: https://docs.python.org/3/library/unittest.mock.html#where-to-patch):

```python
@patch("giza_actions.model.VersionsClient", return_value=b"some bytes")
```

We add a returned value of bytes because it is what `self.version_client.download_original` returns.

Hope this helps @shivam6862

2024-04-24 15:14 UTC, shivam6862 commented
![Screenshot 2024-04-24 200923](https://github.com/gizatechxyz/actions-sdk/assets/115404926/125f0166-d514-43c5-aa21-a0f35c098c92)

@Gonmeso add test case are passed

2024-04-24 16:01 UTC, shivam6862 commented
@Gonmeso done for all file  **run pre-commit run --all-files** which was done previously for **.gitignore**

2024-04-25 09:07 UTC, Gonmeso approved these changes
Thanks for your input!

LGTM!!!!

Great work @shivam6862 ⚡

2024-04-25 09:07 UTC, merged